#!/bin/bash
#$ -V
#$ -cwd
#$ -j y
#$ -N mamba 
#$ -l lilach,h_rt=48:00:00,mem_free=1G
#$ -v popsize=100000
#$ -v murate=0.003
#$ -v recrate=0
#$ -v maxtick=100000
#$ -v s=0.01

## Note that dots are not allowed in script var names

module load R/R215
cd ~/workspace/mamba
R --vanilla --slave -f model.r --args debug=FALSE pop.size=${popsize} mu.rate=${murate} rec.rate=${recrate} s=${s} max.tick=${maxtick}
